const fs=require('fs'),path=require('path'),vm=require('vm');
const ROOT=__dirname;
let c='';for(const f of ['memory.js','mmu.js','rcp.js','cpu.js'])c+=fs.readFileSync(path.join(ROOT,f),'utf8')+'\n';
c+='\nthis.__classes={Memory,MMU,RCP,CPU};\n';
const sb={console,setTimeout:()=>{},clearTimeout:()=>{},performance:{now:()=>Date.now()},Math,Number,BigInt,JSON,DataView,ArrayBuffer,Uint8Array,Uint16Array,Uint32Array,Int8Array,Int16Array,Int32Array,Float32Array,Float64Array,Array};
vm.createContext(sb);vm.runInContext(c,sb,{filename:'c.js'});
const{Memory,MMU,RCP,CPU}=sb.__classes;
const romBuf=fs.readFileSync(path.join(ROOT,'Super Mario 64 (Europe) (En,Fr,De).n64'));
const ab=romBuf.buffer.slice(romBuf.byteOffset,romBuf.byteOffset+romBuf.byteLength);
const ram=new Memory(8*1024*1024);const mmu=new MMU(ram);const rcp=new RCP(mmu,new sb.Uint8Array(320*240*4));const cpu=new CPU(mmu,rcp);
mmu.cpu=cpu;mmu.rcp=rcp;ram.loadRom(ab);cpu.isRunning=true;cpu.performHleBoot();
const hx=a=>Array.from(a).map(x=>x.toString(16).padStart(2,'0')).join(' ');
let wr=0, rd=0;
const _wr=mmu.copyRdramToPif.bind(mmu);
mmu.copyRdramToPif=function(da){_wr(da);wr++;if(wr<=4||(wr%50===0))console.log('WR64B#'+wr+' f3d='+(rcp.f3dTaskCount|0)+' pif[0..16]='+hx(mmu.pifRam.slice(0,16))+' cmd=0x'+mmu.pifRam[63].toString(16));};
const _pj=mmu.processJoybusRead.bind(mmu);
mmu.processJoybusRead=function(){const r=_pj();rd++;if(rd<=4||(rd%50===0))console.log('RD64B#'+rd+' f3d='+(rcp.f3dTaskCount|0)+' active='+r+' ch0Cmds='+mmu.controllerDebug.channel0Cmds+' pif[0..16]='+hx(mmu.pifRam.slice(0,16)));return r;};
for(let s=0;s<26000000;s++)cpu.step();
console.log('final wr='+wr+' rd='+rd+' btnReads='+mmu.controllerDebug.buttonReads+' infoReads='+mmu.controllerDebug.infoReads+' ch0Cmds='+mmu.controllerDebug.channel0Cmds);
